export const searchData = [
  {
    title: "Home",
    description: "Go to the cybersecurity portfolio homepage",
    path: "/",
    keywords: [
      "home",
      "portfolio",
      "resume",
      "cv",
      "rohit kumar",
      "cyber security",
      "cybersecurity analyst",
      "ethical hacker",
      "ceh v13",
      "certified ethical hacker",
      "vapt",
      "penetration testing",
      "web application security",
      "security researcher",
    ],
  },

  {
    title: "About",
    description: "Learn more about my cybersecurity background",
    path: "/about",
    keywords: [
      "about",
      "background",
      "profile",
      "bio",
      "rohit kumar",
      "cyber security analyst",
      "ethical hacker",
      "ceh",
      "ceh v13",
      "security enthusiast",
      "web security",
      "penetration tester",
    ],
  },

  {
    title: "Education",
    description: "View my educational background",
    path: "/education",
    keywords: [
      "education",
      "degree",
      "college",
      "b.com",
      "bachelor of commerce",
      "certified ethical hacker",
      "ceh v13",
      "cyber security certification",
      "security training",
    ],
  },

  {
    title: "Experience",
    description: "Check my cybersecurity experience and practical labs",
    path: "/experience",
    keywords: [
      "experience",
      "career",
      "internship",
      "cyber security",
      "security analyst",
      "vapt engineer",
      "penetration testing",
      "ethical hacking",
      "vulnerability assessment",
      "security testing",
      "web application testing",
    ],
  },

  {
    title: "Skills",
    description: "Explore my cybersecurity skills and tools",
    path: "/skills",
    keywords: [
      "skills",
      "cybersecurity tools",
      "ethical hacking",
      "ceh",
      "vapt",
      "penetration testing",
      "owasp top 10",
      "burp suite",
      "kali linux",
      "nmap",
      "metasploit",
      "wireshark",
      "sql injection",
      "xss",
      "csrf",
      "ssrf",
      "vulnerability assessment",
      "web application security",
    ],
  },

  {
    title: "Projects",
    description: "View cybersecurity projects and penetration testing labs",
    path: "/projects",
    keywords: [
      "projects",
      "security projects",
      "cybersecurity labs",
      "penetration testing",
      "vapt projects",
      "web application security",
      "owasp top 10",
      "burp suite",
      "kali linux",
      "vulnerability assessment",
      "security report",
      "github",
    ],
  },

  {
    title: "Certificates",
    description: "View my cybersecurity certifications and achievements",
    path: "/certificates",
    keywords: [
      "certificates",
      "certifications",
      "ceh",
      "ceh v13",
      "certified ethical hacker",
      "ec council",
      "cybersecurity certification",
      "ethical hacking",
      "security training",
      "achievements",
    ],
  },

  {
    title: "Contact",
    description: "Get in touch for cybersecurity opportunities",
    path: "/contact",
    keywords: [
      "contact",
      "email",
      "hire",
      "job",
      "career",
      "opportunity",
      "cyber security analyst",
      "vapt engineer",
      "penetration tester",
      "collaboration",
      "phone",
      "number",
    ],
  },
];